### ISSUE TITLE
this.___von is not a function

### ISSUE THREAD

**Issue by maxime-gerum** [AngusFu/v-folder#1]
Hello and thank you for your contribution.

I'm using Electron-Vue project : https://www.gitbook.com/book/simulatedgreg/electron-vue/details

And i would like to insert v-folder component.

In basic configuration i have a warn and error

![capture d ecran_2017-04-12_17-48-11](https://cloud.githubusercontent.com/assets/5746824/24966788/379b61d4-1fa8-11e7-8df3-108125383c88.png)

It's important for me can you help me ?

Best regards,

Maxime.

**Comment by AngusFu** [comment]
@Max25190  I'll check it as soon as possible. 

--- updated @2017-04-13-----

I suddenly came up that I've met the same problem when testing about one month ago. Did you follow the instruction in `README.md`?

```js
import VFolder from 'v-folder';
Vue.use(VFolder);
```

Notice that only by `Vue.use` can we correctly use our component. 

If you are introducing this component with following code in your `.vue` file:

```js
// in foo.vue
compoents: {
    'v-folder': VFolder
},
// ....
```
This won't work at all.

**Comment by maxime-gerum** [comment]
Hello, it works,

I had imported with components config and no Vue.use

Thank you AngusFu.

**Comment by AngusFu** [comment]
Happy coding~
