### ISSUE TITLE
filenames that reaches out current CSS container width is not displayed

### ISSUE THREAD

**Issue by prevostcorentin** [AngusFu/v-folder#3]
When I pick up a very long filename when enough place is free in the container it displays correctly:
![selection_004](https://user-images.githubusercontent.com/11979776/33020569-27474b94-cdff-11e7-8907-076a2852e21f.png)

Due to responsive design, container width is updated when reduced. Then the filename does not appear anymore.
![selection_003](https://user-images.githubusercontent.com/11979776/33020606-47a71a86-cdff-11e7-95f2-b34a48b9d517.png)

An option that sets the maximum number of characters which defaults to container width before the name gets shortened is my idea.

**Comment by AngusFu** [comment]
I'll blame this on my CSS code. Long texts just wrapped to another line.  Probably I should use flexbox instead.

**Comment by AngusFu** [comment]
Fixed by using flexbox and `text-overflow: elipsis`.
BTW, other enhancements are on the way.
![image](https://user-images.githubusercontent.com/8180186/33302444-1a8f7c76-d437-11e7-8fab-48a60a8ffb58.png)
